In [1]:
import os
import numpy as np
import pygrib

In [ ]:
path_to_directory = "/mnt/data-weather/moddata"
path_to_save = "/mnt/data-weather/feature/total-precipitation"
feature = "Total Precipitation"
index = 0
directory = os.fsencode(path_to_directory)

for file in os.listdir(directory):
    filename = os.fsdecode(file)
    #print(filename) #prints the filename of every file in "path_to_directory"
    #print(path_to_directory + '/' + filename) #proper path for pygrib
    grbs = pygrib.open(path_to_directory + '/' + filename)
    grb = grbs.select(name = feature)[index]
    data, lats, lons = grb.data(lat1 = 31, lat2 = 41, lon1 = -102, lon2 = -82)
    #print(data.shape, lats.shape, lons.shape, lats.min(), lons.min(), lats.max(), lons.max())
    output = np.stack((data, lats, lons)) #row0 = data, row1 = lat, row2= lon
    np.save(path_to_save + '/' + filename[0:-5], output)
    grbs.close()

In [55]:
grbs = pygrib.open("/mnt/data-weather/moddata/nam_218_20171231_1800_000.grb2")
grb = grbs.select(name = "Total Cloud Cover")[0]
print(grb)
print(grb.values.shape)
data, lats, lons = grb.data(lat1 = 31, lat2 = 41, lon1 = -102, lon2 = -82)
output = np.stack((data,lats,lons))
print(data.shape, lats.shape, lons.shape, lats.min(), lons.min(), lats.max(), lons.max())
print(output.shape)
grbs.close()

442:Total Cloud Cover:% (instant):lambert:unknown:level 0 considered as a single layer:fcst time 0 hrs:from 201712311800
(428, 614)
(13999,) (13999,) (13999,) 31.001285230157098 -101.99925781682273 40.99968777669306 -82.0002706763687
(3, 13999)


In [22]:
grbs = pygrib.open("/mnt/data-weather/moddata/nam_218_20171231_1800_001.grb2")
print(grbs.select(name="Total Cloud Cover"))
print(grbs.select(name="Total Cloud Cover")[0].values)
grbs.close()

[448:Total Cloud Cover:% (instant):lambert:unknown:level 0 considered as a single layer:fcst time 1 hrs:from 201712311800]
[[  0.   0.   0. ...  36.  25.  18.]
 [  2.   1.   0. ...  26.  27.  27.]
 [ 10.  11.  10. ...  40.  40.  40.]
 ...
 [ 22.  34.  45. ... 100. 100. 100.]
 [ 15.  27.  45. ... 100. 100. 100.]
 [  8.  19.  42. ...  98. 100. 100.]]


In [23]:
grbs = pygrib.open("/mnt/data-weather/moddata/nam_218_20171231_1800_002.grb2")
print(grbs.select(name="Total Cloud Cover"))
print(grbs.select(name="Total Cloud Cover")[0].values)
grbs.close()

[448:Total Cloud Cover:% (instant):lambert:unknown:level 0 considered as a single layer:fcst time 2 hrs:from 201712311800]
[[ 11.  11.   4. ...  39.  29.  24.]
 [ 13.  12.   3. ...  32.  31.  30.]
 [ 18.  21.  10. ...  37.  39.  39.]
 ...
 [ 11.  20.  29. ... 100. 100. 100.]
 [ 16.  24.  29. ... 100. 100. 100.]
 [ 16.  29.  32. ... 100. 100. 100.]]


In [24]:
grbs = pygrib.open("/mnt/data-weather/moddata/nam_218_20171231_1800_003.grb2")
print(grbs.select(name="Total Cloud Cover"))
print(grbs.select(name="Total Cloud Cover")[0].values)
grbs.close()

[448:Total Cloud Cover:% (instant):lambert:unknown:level 0 considered as a single layer:fcst time 3 hrs:from 201712311800]
[[ 41.  38.  19. ...  53.  47.  20.]
 [ 48.  45.  18. ...  53.  48.  34.]
 [ 34.  31.  12. ...  53.  52.  43.]
 ...
 [ 21.  32.  39. ... 100. 100. 100.]
 [ 25.  37.  47. ... 100. 100. 100.]
 [ 26.  38.  48. ... 100. 100. 100.]]


In [27]:
grbs = pygrib.open("/mnt/data-weather/moddata/nam_218_20171231_1800_006.grb2")
print(grbs.select(name="Total Cloud Cover"))
print(grbs.select(name="Total Cloud Cover")[0].values)
grbs.close()

[448:Total Cloud Cover:% (instant):lambert:unknown:level 0 considered as a single layer:fcst time 6 hrs:from 201712311800]
[[  0.   0.   0. ...   0.   7.  12.]
 [  0.   0.   0. ...   6.  12.  22.]
 [  0.   0.  10. ...  12.  24.  50.]
 ...
 [ 78.  78.  69. ... 100. 100. 100.]
 [ 85.  85.  71. ... 100. 100. 100.]
 [ 84.  87.  70. ... 100. 100. 100.]]
